name: Build and Deploy
on:
  push:
    branches:
      - main
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install and Build 🔧
        working-directory: ./app
        run: |
          npm i
          npm ci
          npm run build

      - name: Deploy 🚀 test
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./frontend/build
          token: ${{ secrets.DEPLOY_TOKEN }} 
